export const DISPLAY_LOGIN_MODAL = "DISPLAY_MODAL";
export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL";
export const DISPLAY_SIGN_UP_MODAL = "DISPALY_SIGN_UP_MODAL";
export const HIDE_SIGN_UP_MODAL = "HIDE_SIGN_UP_MODAL";
